<a href="https://colab.research.google.com/github/Akash-9794/numpy-100-challenges/blob/main/problems/level1_basics/problem_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create the following arrays:
1. 1D array: [1, 2, 3, 4, 5]
2. 2D array: [[1, 2, 3],
              [4, 5, 6]]
3. Array of zeros: 3x3
4. Array of ones: 2x4
5. Array from 0 to 9

In [9]:
import numpy as np

oneD = np.array([1,2,3,4,5])
twoD = np.array([[1,2,3],
                [4,5,6]])
arrOfZeros = np.zeros((3,3))
arrOfOnes = np.ones((2,4))
rang = np.arange(0,10)

print(oneD)
print(twoD)
print(arrOfZeros)
print(arrOfOnes)
print(rang)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
