<a href="https://colab.research.google.com/github/Akash-9794/numpy-100-challenges/blob/main/problems/level_2/016.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NOTES

In [ ]:
# ================================================
# NUMPY NOTES — Combined Indexing
# ================================================

import numpy as np

arr = np.array([[1,  2,  3,  4,  5],
                [6,  7,  8,  9,  10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

# ── COMBINING SLICING + FANCY ─────────────────
# Select specific rows → then slice columns
print(arr[[0,2,4], 1:4])
# rows 0,2,4 → cols 1,2,3
# [[ 2  3  4]
#  [12 13 14]
#  [22 23 24]]

# ── COMBINING BOOLEAN + FANCY ─────────────────
data = np.array([10, 25, 5, 30, 15, 40])
mask = data > 15
indices = np.where(mask)[0]     # get indices
print(indices)                   # [1 3 5]
print(data[indices])             # [25 30 40]

# ── STEP SLICING ON 2D ────────────────────────
# Every other row, every other column
print(arr[::2, ::2])
# [[ 1  3  5]
#  [11 13 15]
#  [21 23 25]]

# ── ML CONTEXT ────────────────────────────────
np.random.seed(42)
dataset = np.random.rand(10, 5)
labels  = np.array([0,1,0,1,1,0,1,0,1,0])

# Get only class 1 samples, first 3 features
class1_samples = dataset[labels == 1]
class1_features = class1_samples[:, :3]
print(f"Class 1 shape: {class1_features.shape}")

# Get every 2nd sample, last 2 features
sampled = dataset[::2, -2:]
print(f"Sampled shape: {sampled.shape}")

#Problem  #016 — Combined Indexing :

In [ ]:
import numpy as np

arr = np.array([[1,  2,  3,  4,  5],
                [6,  7,  8,  9,  10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

# Q1: Select rows 1,3 and columns 0,2,4

# Q2: Get every other row, all columns

# Q3: Get every other row, every other column

# Q4: ML Task! 🔥
np.random.seed(42)
dataset = np.random.rand(8, 6)
labels  = np.array([0,1,1,0,1,0,1,0])

# a) Get all class 1 samples
# b) From class 1 samples get first 3 features only
# c) Print final shape

#Solution


In [ ]:
import numpy as np

arr = np.array([[1,  2,  3,  4,  5],
                [6,  7,  8,  9,  10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

# Q1: Select rows 1,3 and columns 0,2,4

print(arr[[1,3],::2])

# Q2: Get every other row, all columns

print(arr[::2])

# Q3: Get every other row, every other column

print(arr[::2,::2])

# Q4: ML Task! 🔥
np.random.seed(42)
dataset = np.random.rand(8, 6)
labels  = np.array([0,1,1,0,1,0,1,0])

# a) Get all class 1 samples
# b) From class 1 samples get first 3 features only
# c) Print final shape

class1_samples = dataset[labels == 1]
class1_features = class1_samples[:, :3]
print(class1_features.shape)
