<a href="https://colab.research.google.com/github/Akash-9794/numpy-100-challenges/blob/main/problems/level_1/problem_006.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problem #006 Ready! 🔥
Topic: zeros, ones, full, eye — Deep Patterns

In [ ]:
# ================================================
# NUMPY NOTES — zeros, ones, full, eye patterns
# ================================================

import numpy as np

# ── zeros ─────────────────────────────────────
# Creates array filled with 0.0 (float64 default)

z1 = np.zeros(5)           # 1D: [0. 0. 0. 0. 0.]
z2 = np.zeros((3,3))       # 2D: 3x3 matrix
z3 = np.zeros((2,3,4))     # 3D: depth=2, rows=3, cols=4

# ML Use: initialize weights before training
weights = np.zeros((784, 128))  # neural network layer

# ── ones ──────────────────────────────────────
# Creates array filled with 1.0 (float64 default)

o1 = np.ones(5)            # [1. 1. 1. 1. 1.]
o2 = np.ones((3,3))        # 3x3 matrix of ones

# ML Use: initialize bias terms
bias = np.ones((128,))

# ── full ──────────────────────────────────────
# Creates array filled with ANY value you choose

f1 = np.full(5, 7)         # [7 7 7 7 7]
f2 = np.full((3,3), 99)    # 3x3 filled with 99
f3 = np.full((2,4), 0.5)   # 2x4 filled with 0.5

# ML Use: initialize with specific values
mask = np.full((28,28), 255)  # white image mask

# ── eye ───────────────────────────────────────
# Creates identity matrix (1s on diagonal)

e1 = np.eye(3)             # 3x3 identity
e2 = np.eye(4)             # 4x4 identity
e3 = np.eye(3, 4)          # 3x4 (non-square!)

print("3x3 Identity:")
print(e1)
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

# ML Use: one-hot encoding, linear algebra
# In math: A × I = A (identity property!)

# ── PATTERNS ──────────────────────────────────
# zeros_like → same shape as existing array!
arr = np.array([[1,2,3],[4,5,6]])
z_like = np.zeros_like(arr)   # same shape, all zeros
o_like = np.ones_like(arr)    # same shape, all ones

print("\nOriginal shape:", arr.shape)
print("zeros_like:\n", z_like)
print("ones_like:\n", o_like)

#Problem #006

In [ ]:
import numpy as np

# Q1: Create weight matrix for neural network
#     Input layer:  512 neurons
#     Output layer: 256 neurons
#     Initialize with zeros

# Q2: Create 5x5 identity matrix
#     Then verify diagonal is all 1s
#     (Hint: use np.diag())

# Q3: Create 4x4 matrix filled with 0.5
#     Then convert to float32

# Q4: Using zeros_like and ones_like
#     Given array:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])
#     Create zero copy and ones copy
#     Print both shapes — are they same?

# Q5: ML Challenge! 🔥
#     Create a 10x10 confusion matrix template
#     filled with zeros, dtype=int
#     Then print:
#     → shape
#     → dtype
#     → total elements

#Solution

In [ ]:
import numpy as np

# Q1: Create weight matrix for neural network
#     Input layer:  512 neurons
#     Output layer: 256 neurons
#     Initialize with zeros

arr1 = np.zeros((512,256))
# print(arr1)

# Q2: Create 5x5 identity matrix
#     Then verify diagonal is all 1s
#     (Hint: use np.diag())

arr2 = np.eye(5,5)

# print(np.diag(arr2))
# print(arr2)

# Q3: Create 4x4 matrix filled with 0.5
#     Then convert to float32

arr3 = np.full((4,4),0.5).astype(np.float32)
# print(arr3)

# Q4: Using zeros_like and ones_like
# zeros_like → same shape as existing array!
#     Given array:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])
#     Create zero copy and ones copy
#     Print both shapes — are they same?

arr4 = np.zeros_like(arr) # same shape, all zeros
arr5 = np.ones_like(arr)   # same shape, all ones
print(arr4)
print(arr5)

# Q5: ML Challenge! 🔥
#     Create a 10x10 confusion matrix template
#     filled with zeros, dtype=int
#     Then print:
#     → shape
#     → dtype
#     → total elements

num_classes = 10
conf_matrix = np.zeros((num_classes,num_classes),dtype=int)
# print(conf_matrix.shape)
# print(conf_matrix.dtype)
# print(conf_matrix.size)
