<a href="https://colab.research.google.com/github/Akash-9794/numpy-100-challenges/blob/main/problems/level_3/030.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏆 FINAL BOSS — Problem #030!


In [ ]:
import numpy as np
np.random.seed(42)

# ═══════════════════════════════════════════
# LEVEL 3 FINAL BOSS
# Build Complete Neural Network from scratch!
# Input → Hidden Layer → Output
# ═══════════════════════════════════════════

# Dataset: XOR problem
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([0, 1, 1, 0])  # XOR labels

# ── CHALLENGE 1: Initialize ───────────────
# W1 shape = (2, 4)  → input to hidden
# b1 shape = (4,)    → hidden bias
# W2 shape = (4, 1)  → hidden to output
# b2 shape = (1,)    → output bias
# Use np.random.randn * 0.1 for weights
# Use np.zeros for biases
np.random.seed(42)
# YOUR CODE:

# ── CHALLENGE 2: Activation Functions ────
# Implement sigmoid and its derivative!
def sigmoid(x):
    # YOUR CODE:
    pass

def sigmoid_derivative(x):
    # Hint: sigmoid(x) * (1 - sigmoid(x))
    # YOUR CODE:
    pass

# ── CHALLENGE 3: Forward Pass ─────────────
# hidden = sigmoid(X @ W1 + b1)
# output = sigmoid(hidden @ W2 + b2)
# YOUR CODE:

# ── CHALLENGE 4: Loss ─────────────────────
# MSE loss between output and y
# YOUR CODE:

# ── CHALLENGE 5: Training Loop ────────────
# Train 1000 epochs
# Forward pass → Loss → Print every 200 epochs
# YOUR CODE:

# ── CHALLENGE 6: Evaluate ─────────────────
# Final predictions → round to 0 or 1
# Print predicted vs actual
# Calculate accuracy
# YOUR CODE:

#Solution


In [14]:
import numpy as np
np.random.seed(42)

# ═══════════════════════════════════════════
# LEVEL 3 FINAL BOSS
# Build Complete Neural Network from scratch!
# Input → Hidden Layer → Output
# ═══════════════════════════════════════════

# Dataset: XOR problem
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([0, 1, 1, 0])  # XOR labels

# ── CHALLENGE 1: Initialize ───────────────
# W1 shape = (2, 4)  → input to hidden
# b1 shape = (4,)    → hidden bias
# W2 shape = (4, 1)  → hidden to output
# b2 shape = (1,)    → output bias
# Use np.random.randn * 0.1 for weights
# Use np.zeros for biases
np.random.seed(42)
# YOUR CODE:

W1 = np.random.randn(2,4)*0.1
b1 = np.zeros(4)
W2 = np.random.randn(4,1)*0.1
b2 = np.zeros(1)

print(f"W1: {W1.shape}")
print(f"b1: {b1.shape}")
print(f"W2: {W2.shape}")
print(f"b2: {b2.shape}")

# ── CHALLENGE 2: Activation Functions ────
# Implement sigmoid and its derivative!
def sigmoid(x):
    # YOUR CODE:
    return 1 / (1 + np.exp(-x))


def sigmoid_derivative(x):
    # Hint: sigmoid(x) * (1 - sigmoid(x))
    # YOUR CODE:
    return sigmoid(x)*(1 - sigmoid(x))

z = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
print(sigmoid(z))
print(sigmoid_derivative(z))

# ── CHALLENGE 3: Forward Pass ─────────────
# hidden = sigmoid(X @ W1 + b1)
# output = sigmoid(hidden @ W2 + b2)
# YOUR CODE:
hidden = sigmoid(X @ W1 + b1)
output = sigmoid(hidden @ W2 + b2)

print(f"Hidden shape: {hidden.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n{output}")

# ── CHALLENGE 4: Loss ─────────────────────
# MSE loss between output and y
# YOUR CODE:

loss = np.mean((output - y.reshape(-1,1))**2)
print(f"Initial Loss: {loss:.4f}")

# ── CHALLENGE 5: Training Loop ────────────
# Train 1000 epochs
# Forward pass → Loss → Print every 200 epochs
# YOUR CODE:

for epoch in range(1000):
  hidden = sigmoid(X @ W1 + b1)
  output = sigmoid(hidden @ W2 + b2)

  loss = np.mean((output - y.reshape(-1,1))**2)
  if epoch % 200 == 0:
        print(f"Epoch {epoch}: Loss={loss:.4f}")

# ── CHALLENGE 6: Evaluate ─────────────────
# Final predictions → round to 0 or 1
# Print predicted vs actual
# Calculate accuracy
# YOUR CODE:

final_hidden = sigmoid(X @ W1 + b1)
final_output = sigmoid(final_hidden @ W2 + b2)
predicted = np.round(final_output)

print("Predicted vs Actual:")
for i in range(len(X)):
    print(f"Input: {X[i]} → Predicted: {int(predicted[i][0])} | Actual: {int(y[i])}")

accuracy = np.mean(predicted == y.reshape(-1,1))
print(f"Accuracy: {accuracy:.2f}")

W1: (2, 4)
b1: (4,)
W2: (4, 1)
b2: (1,)
[0.11920292 0.26894142 0.5        0.73105858 0.88079708]
[0.10499359 0.19661193 0.25       0.19661193 0.10499359]
Hidden shape: (4, 4)
Output shape: (4, 1)
Output:
[[0.48930086]
 [0.48861078]
 [0.48847867]
 [0.4877922 ]]
Initial Loss: 0.2501
Epoch 0: Loss=0.2501
Epoch 200: Loss=0.2501
Epoch 400: Loss=0.2501
Epoch 600: Loss=0.2501
Epoch 800: Loss=0.2501
Predicted vs Actual:
Input: [0 0] → Predicted: 0 | Actual: 0
Input: [0 1] → Predicted: 0 | Actual: 1
Input: [1 0] → Predicted: 0 | Actual: 1
Input: [1 1] → Predicted: 0 | Actual: 0
Accuracy: 0.5000
